name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

# We use dylan-tool here so that the library will be tested with the package
# deps specified in pkg.json.

jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:

      - uses: dylan-lang/install-dylan-tool@v1

      - name: Create workspace
        run: |
          ./dylan new workspace work

      - uses: actions/checkout@v2
        with:
          path: work/workspaces

      - name: Build workspaces-test-suite
        run: |
          cd work
          ../dylan update
          ../dylan-compiler -build -jobs 3 workspaces-test-suite

      - name: Run workspaces-test-suite
        run: |
          cd work
          # Test suite creates a workspace in the ${DYLAN}/_test directory and
          # workspaces can't be nested, so set $DYLAN outside the workspace.
          DYLAN=${PWD}/.. _build/bin/workspaces-test-suite
